name: HV Web App Health Check

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Test Repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytest
      - name: Run The Test
        env:
          HV_ME_WEBSITE_URL_PROD: ${{secrets.HV_ME_WEBSITE_URL_PROD}}
        run: |
          pytest -s tests/test_health_check.py
